import Head from "next/head";
import CarForm from "../lib/CarForm";
import SearchForm from "../lib/SearchForm";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Full Stack Next JS and Redis Full Text Search App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Full Stack Next JS and Redis Full Text Search App
        </h1>

        <h2>Create a Car</h2>
        <CarForm />

        <hr />

        <h2>Search for a Car</h2>
        <SearchForm />
      </main>
    </div>
  );
}
